---
- name: "Setup SSH key on VM"
  hosts: all
  gather_facts: no

  tasks:
    - name: "Add new host" 
      add_host:
        name: '{{ ip_address }}'
        groups: vm

    - name: Write the host key to known hosts
      connection: local
      shell: "ssh-keyscan -H {{ ip_address }} >> /home/semaphore/.ssh/known_hosts"

    - name: Write the host ip address to inventory file
      connection: local
      shell: "echo {{ ip_address }} >> /inventory/PhoneSystems.ini"

- hosts: vm
  remote_user: root
  gather_facts: yes

  tasks:
    - name: "Ping the VM to ensure access"
      ping:

    - name: Add SSH key to authorized_keys
      authorized_key:
        user: "root"
        key: https://github.com/jidland12.keys
        state: present

    - name: Disable password authentication in sshd_config
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication'
        line: 'PasswordAuthentication no'
      notify: Restart SSH Service

    - name: Ensure PubkeyAuthentication is set to yes
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PubkeyAuthentication'
        line: 'PubkeyAuthentication yes'
      notify: Restart SSH Service

  handlers:
    - name: Restart SSH Service
      service:
        name: sshd
        state: restarted