---
- name: "Setup VM for Initial Creation"
  hosts: all
  gather_facts: no

  tasks:
    - name: "Add new host" 
      add_host:
        name: '{{ ip_address }}'
        groups: vm

- hosts: vm
  remote_user: root
  gather_facts: no

  tasks:
    - name: Write the new host key to known hosts
      connection: local
      shell: "ssh-keyscan -H {{ ip_address }} >> /home/semaphore/.ssh/known_hosts"

    - name: "Ping the VM to ensure access"
      ping: